# Generated by Django 3.2.9 on 2021-11-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member',
            field=models.CharField(default='Faculty', max_length=20),
        ),
    ]
