# Generated by Django 3.2.9 on 2021-11-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
