# Generated by Django 3.2.9 on 2021-11-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
