# Generated by Django 3.2.9 on 2021-11-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211106_0704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
